server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5002/users
    driver-class-name: org.postgresql.Driver
    username: pguser
    password: pgpass
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        default_schema: users_scheme
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true