server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        default_schema: users_scheme
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true