server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: users_scheme
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        default_schema: users_scheme
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true